feat(docker-codebuild): factory helper for using authentication and DockerHub images in CodeBuild
ndlib/ndlib-cdk pull request #53
Opened 2021-03-03 21:42 UTC by ialford

This method provides a simpler way to create a CodeBuild project that uses authenticated pulls from DockerHub. It does not affect the base CDK constructs, but rather allows the CodeBuilds to be made by only passing in two strings to the method.

Closes #43

2021-03-03 22:04 UTC, mlkirkpatrick requested changes

2021-03-03 22:04 UTC, mlkirkpatrick commented on src/docker-codebuild-action.ts
> +export class DockerCodeBuildAction extends PipelineProject {
I don't think you want to extend PipelineProject. It's most likely used in that context, but you don't need the PipelineProject behavior; these functions can probably just be a static class.

2021-03-04 15:52 UTC, rdoughty approved these changes

2021-03-04 15:54 UTC, mlkirkpatrick commented
Could you update the `fromWindowsDockerImage` to use `IDockerCodeBuildAction` as well?

2021-03-04 15:56 UTC, SteveMattison approved these changes

2021-03-04 15:59 UTC, ialford commented
> Could you update the `fromWindowsDockerImage` to use `IDockerCodeBuildAction` as well?

![bitmoji](https://sdk.bitmoji.com/render/panel/626dd453-b50e-4ee9-9dce-86d306043c85-452e69cc-d6b7-44e3-b5df-ebedb039ee5a-v1.png?transparent=1&palette=1&width=246)

Done.

2021-03-08 16:16 UTC, mlkirkpatrick reviewed
Just some updates to the README then looks good!

2021-03-08 16:16 UTC, mlkirkpatrick commented on README.md
> +    ),
Update this

2021-03-08 16:16 UTC, mlkirkpatrick commented on README.md
> +    ),
Update this

2021-03-08 16:22 UTC, ialford commented on README.md
> +    ),
These have been updated from the previous version where it was just using a straight string. Was there something more that needed to be changed that I am missing?

2021-03-08 16:24 UTC, mlkirkpatrick commented on README.md
> +    ),
No, that's all. I was just referring to the proper syntax for the new method signature. :)

2021-03-08 18:37 UTC, ialford commented on README.md
> +    ),
Yeah, this is the updated syntax, matching what is used in the unit tests. If it's not what was expected or is unclear, let me know what else needs to be done.

2021-03-08 18:39 UTC, mlkirkpatrick commented on README.md
> +    ),
It's missing the braces to make the 3rd parameter an actual object.

2021-03-08 18:45 UTC, ialford commented on README.md
> +    ),
Good catch, have updated.

2021-03-08 18:45 UTC, ialford commented on README.md
> +    ),
Good catch, have updated.

2021-03-08 19:02 UTC, mlkirkpatrick approved these changes

2021-03-08 19:24 UTC, merged