Add Edge Lambda constructs.
ndlib/ndlib-cdk pull request #56
Opened 2021-04-26 18:42 UTC by mlkirkpatrick

This adds 2 edge lambdas which can be reused in multiple projects. Including them as constructs allows us to define specific properties (passed as environment variables) that the lambda code depends on, in essence allowing for variation without duplicating code.

2021-04-26 18:50 UTC, mlkirkpatrick commented
There is an issue with CI for Node 10 because `String.prototype.matchAll` was implemented in Node 12.0.0. I don't see any reason that we would want to run this library on Node 10 given that AWS is deprecating it within the next few months. Can we simply remove node 10 from the CI workflow?

2021-04-26 19:22 UTC, ialford commented
> There is an issue with CI for Node 10 because `String.prototype.matchAll` was implemented in Node 12.0.0. I don't see any reason that we would want to run this library on Node 10 given that AWS is deprecating it within the next few months. Can we simply remove node 10 from the CI workflow?

I'm not on the core team, but I have no concerns about it.

2021-04-26 19:39 UTC, SteveMattison commented
I think you should remove Node 10 from the CI workflow.

2021-04-26 19:53 UTC, SteveMattison approved these changes

2021-04-27 13:17 UTC, jgondron requested changes
Since this is our first exploration of providing lambdas as reusable pieces, you may need to do some work on how everything gets packaged. Atm, it only packages up the js that tsc outputs to the lib directory https://github.com/ndlib/ndlib-cdk/blob/master/package.json#L52, so I don't think it will pick up the lambda source without making some additional changes.

2021-04-27 18:32 UTC, mlkirkpatrick commented
> Since this is our first exploration of providing lambdas as reusable pieces, you may need to do some work on how everything gets packaged. Atm, it only packages up the js that tsc outputs to the lib directory https://github.com/ndlib/ndlib-cdk/blob/master/package.json#L52, so I don't think it will pick up the lambda source without making some additional changes.

Good catch!

I added a script to the build which will copy everything from the lambda "src" folders to their respective location under /lib/. This _should_ do the trick. I wanted to keep it flexible so that multi-file lambdas won't be an issue, and even if the lambda requires node_modules of its own (or is written in another language like python), everything will be included.

2021-04-27 19:49 UTC, jgondron approved these changes

2021-04-27 19:56 UTC, merged